from . import gamebuttons as buttons
from . import gamesliders as sliders
from . import gametextinputs as textinputs
from . import gamedropdowns as dropdowns
from . import gamedivs as divs
from . import gametablesources as tablesources
from . import gametables as tables
from . import gametext as text
from . import gamelabels as labels
